INPUT:
  TRAIN: ''
  TEST: ''

TRAINING:
    TRAINING_SET: 'ps-dataset'
    EXPERIMENT_NAME: 'less_augmentations'
    MODEL_DIR: 'models'
    MODEL: 'init'
    CUDA: True
    GPU_ID: 0
    SEED: 42
    INPUT_LAYER: 1
    IMAGE_SIZE_H: 256
    IMAGE_SIZE_W: 256
    LOAD_PRE_TRAINING: False
    LEAARNING_RATE: 0.001
    START_EPOCH: 0
    END_EPOCHS: 200
    NMS_EPOCH0: 10
    NMS_OTHERS: 10
    BATCH_SIZE: 20
    DISTANCE_THRESHOLD: 3
    PLOT_EVERY_X_BATCHES: 10
    OPTIMIZER: Adam
    BASE_LR: 0.001
    SAVE_MODEL_STEP: 5
    NUM_WORKERS: 8

    AUGMENTATION:
      AUGMENTATION_LIST:
        - additive_gaussian_noise
        - random_brightness
        - random_contrast
        - add_shade
        - motion_blur
        - gamma_correction
        - opposite
        - no_aug

      ADDITIVE_GAUSSIAN_NOISE:
        STD_MIN: 0
        STD_MAX: 1
      ADDITIVE_SPECKLE_NOISE:
        INTENSITY: 5
      MOTION_BLUR:
        MAX_KSIZE: 15
      GAMMA_CORRECTION:
        MIN_GAMMA: 0.5
        MAX_GAMMA: 1.5

    SAMPLE_HOMOGRAPHY:
        SCALING:
          USE_SCALING: True
          MIN_SCALING_X: 0.8
          MAX_SCALING_X: 1.3
          MIN_SCALING_Y: 0.8
          MAX_SCALING_Y: 1.3
        PERSPECTIVE:
          USE_PERSPECTIVE: True
          MIN_PERSPECTIVE_X: 0.000001
          MAX_PERSPECTIVE_X: 0.0005
          MIN_PERSPECTIVE_Y: 0.000001
          MAX_PERSPECTIVE_Y: 0.0005
        TRANSLATION:
          USE_TRANSLATION: True
          MAX_HORIZONTAL_DIS: 20
          MAX_VERTICAL_DIS: 20
        SHEARING:
          USE_SHEARING: True
          MIN_SHEARING_X: -0.2
          MAX_SHEARING_X: 0.2
          MIN_SHEARING_Y: -0.2
          MAX_SHEARING_Y: 0.2
        ROTATION:
          USE_ROTATION: True
          MAX_ANGLE: 30

TEST:
    IMAGE_SIZE_H: 256
    IMAGE_SIZE_W: 256
    TESTING: True
    TESTING_EVERY: 1
    NMS: 10
    BATCH_SIZE: 5
    MIN_PROB: 0.5
    WEIGHTS: 'weights/ps-dataset_train_epoch_75.tar'

LOGGING:

  ENABLE_LOGGING: True
  LOG_DIR: 'logs/'
  LOG_INTERVAL: 1